title: Subcommission on Stratigraphic Classification
email: nick@kurrawong.ai
description: >- # this means to ignore newlines until "baseurl:"
  The Subcommission represents a core business for the International Commission on 
  Stratigraphy the primary body for creating, discussing, publishing and disseminating 
  an internationally agreed-upon guide on stratigraphic terminology and classification 
  or-in other words standardization of the Stratigraphic Units.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
